name: Build site with gulp and deploy

on:
  push:
    branches:
      - github-actions-build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 11.15.0
    - name: Install dependencies
      run: npm install
    - name: Compile site to docs folder
      run: gulp build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: /docs
        keep_files: true
