name: Build site with gulp and deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 11.15.0
    - name: Install dependencies
      run: npm install
    - name: Compile site
      run: gulp build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs #this might not be needed as not deploying to /docs now
        keep_files: true
        cname: mapswipe.org
